hero_image: images/banner.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Tegnekasse
description: I dette projekt skal du lave dit eget tegneprogram!
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: art
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Tegnekasse