---
hero_image: images/banner.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Malkasten
description: Lerne dein eigenes Malprogramm zu machen.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: art
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - title: Einleitung
  - title: Was du brauchen wirst
  - title: Einen Stift machen
  - title: Buntstifte
  - title: Fehler machen
  - title: Die Stiftdicke ändern
  - title: 'Zusatzaufgabe: Tastenkürzel'
  - title: 'Zusatzaufgabe: mehr Stifte'
