---
hero_image: images/banner.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Kutija sa bojama
description: Nauči kako da napraviš sopstveni program za crtanje.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: art
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - title: Uvod
  - title: Šta će ti biti potrebno
  - title: Pravljenje olovke
  - title: Olovke u bojama
  - title: Greške
  - title: Promjena debljine olovke
  - title: 'Izazov: prečice'
  - title: 'Izazov: više olovaka'
